name: "qhub auto update"

on:
  pull_request:
    branches:
      - master
    paths:
      - "qhub-config.yaml"

jobs:
  build:
    name: qhub
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Image'
        uses: actions/checkout@master
        with:
          token: {{ '${{ secrets.REPOSITORY_ACCESS_TOKEN }}' }}
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install qhub
        run: |
          pip install qhub
      - name: Validate config file
        run: |
          qhub validate qhub-ops-config.yaml
  